# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package
on:
  release:
    types: [created]
  pull_request: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pytest
      - name: Prepare version
        run: |
          echo "Version number: ${GITHUB_REF##*/}"
          echo "${GITHUB_REF##*/}" > package_version.txt || exit $?
          ls
        env:
          GITHUB_BRANCH: ${{ github.ref }}
      - name: Run pytest
        run: |
          pytest ./zthreading
        env:
          GITHUB_BRANCH: ${{ github.ref }}

      - name: Build
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish
        if: github.event_name == 'release'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
